#include "sortA.h"
#include "sortB.h"
#include "sortC.h"
#include "sortD.h"
#include <getopt.h>
#include <inttypes.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#define OPTIONS "Aabcdp:r:n:"
#define DEFAULT_SEED 8222022
#define DEFAULT_PRINT 100
#define DEFAULT_ARRAY 100

uint32_t move_a;
uint32_t compare_a;
uint32_t move_b;
uint32_t compare_b;
uint32_t move_c;
uint32_t compare_c;
uint32_t move_d;
uint32_t compare_d;

uint32_t *array_create(uint32_t num_array);
void array_delete(uint32_t *array);
void array_print(uint32_t *array, uint32_t length);

// Main Function
// Use getopt and command line to provide correct output
// If User provides a wrong command, program will show error and exit
int main(int argc, char *argv[]) {
  int ch;
  // Use bool to determine the option which selected by user
  bool sa_check = false;
  bool sb_check = false;
  bool sc_check = false;
  bool sd_check = false;
  // Set seed, num of print element and array to default value
  uint32_t random_seed = DEFAULT_SEED;
  uint32_t num_print = DEFAULT_PRINT;
  uint32_t num_array = DEFAULT_ARRAY;
  if (argc == 1) {
    printf("Input Error, you must provide at least one option\n");
    return 0;
  }
  while ((ch = getopt(argc, argv, OPTIONS)) != -1) {
    switch (ch) {
    case 'A':
      sa_check = true;
      sb_check = true;
      sc_check = true;
      sd_check = true;
      break;

    case 'a':
      sa_check = true;
      break;

    case 'b':
      sb_check = true;
      break;

    case 'c':
      sc_check = true;
      break;

    case 'd':
      sd_check = true;
      break;

    case 'r':
      random_seed = atoi(optarg);
      break;

    case 'p':
      num_print = atoi(optarg);
      break;

    case 'n':
      num_array = atoi(optarg);
      if (num_array < 1) {
        printf("Num of array should bigger than 1\n");
        return 0;
      }
      break;

    default:
      printf("Please provide useful command!(-A -a -b -c -d -r: -p: -n:)\n");
      return 0;
    }
  }

  // If no option is selected, show error and exit
  if (!sa_check && !sb_check && !sc_check && !sd_check) {
    printf("You have to provide at least one option! (-a -b -c -d -A)\n");
    return 0;
  }
  // If num of print is bigger than num of array
  // We should set num of print equals to length of array
  if (num_print > num_array) {
    num_print = num_array;
  }

  // Sorting
  // Create an array by using random seed
  // Sort by using methods
  // Delete Array
  // This operation is used for all sorting method
  //

  // Do sorting A if choosed
  if (sa_check) {
    srand(random_seed);
    uint32_t *array_a = array_create(num_array);
    sort_A(array_a, num_array);
    printf("Sort A\n");
    printf("%u elements\n", num_array);
    printf("%u moves\n", move_a);
    printf("%u compares\n", compare_a);
    array_print(array_a, num_print);
    printf("\n");
    array_delete(array_a);
  }
  // Do sorting B if choosed
  if (sb_check) {
    srand(random_seed);
    uint32_t *array_b = array_create(num_array);
    sort_B(array_b, num_array);
    printf("Sort B\n");
    printf("%u elements\n", num_array);
    printf("%u moves\n", move_b);
    printf("%u compares\n", compare_b);
    array_print(array_b, num_print);
    printf("\n");
    array_delete(array_b);
  }
  // Do sorting C if choosed
  if (sc_check) {
    srand(random_seed);
    uint32_t *array_c = array_create(num_array);
    sort_C(array_c, num_array);
    printf("Sort C\n");
    printf("%u elements\n", num_array);
    printf("%u moves\n", move_c);
    printf("%u compares\n", compare_c);
    array_print(array_c, num_print);
    printf("\n");
    array_delete(array_c);
  }
  // Do sorting D if choosed
  if (sd_check) {
    srand(random_seed);
    uint32_t *array_d = array_create(num_array);
    sort_D(array_d, num_array);
    printf("Sort D\n");
    printf("%u elements\n", num_array);
    printf("%u moves\n", move_d);
    printf("%u compares\n", compare_d);
    array_print(array_d, num_print);
    printf("\n");
    array_delete(array_d);
  }
  return 0;
}

// Array Create
// Fill the array by using random number generated by rand
// Use bit mask to limit the number up to 24 bits
uint32_t *array_create(uint32_t num_array) {
  uint32_t *array = calloc(num_array, sizeof(uint32_t));
  if (array == NULL) {
    exit(1);
  }
  for (uint32_t i = 0; i < num_array; i++) {
    uint32_t rand_num = rand();
    array[i] = rand_num &= 0x00ffffff;
  }
  return array;
}

// Array Delete
// Free the memory which allocated for array
void array_delete(uint32_t *array) {
  free(array);
  array = NULL;
  return;
}

// Array Print
//
// length: num of array which needs to print
//
// Prints the array by using specific format
void array_print(uint32_t *array, uint32_t length) {
  for (uint32_t i = 0; i < length; i++) {
    if (i != 0 && i % 7 == 0) {
      printf("\n");
    }
    printf("  %8u", array[i]);
  }
}
